{
  "schema_version": "1.4.0",
  "id": "GHSA-cf74-x979-rggp",
  "modified": "2022-05-24T17:26:02Z",
  "published": "2022-05-24T17:26:02Z",
  "aliases": [
    "CVE-2020-24372"
  ],
  "details": "LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in lj_err.c.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-24372"
    },
    {
      "type": "WEB",
      "url": "https://github.com/LuaJIT/LuaJIT/issues/603"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2020-08-17T17:15:00Z"
  }
}