{
  "schema_version": "1.4.0",
  "id": "GHSA-8fww-64cx-x8p5",
  "modified": "2023-03-27T21:31:53Z",
  "published": "2023-03-26T21:30:23Z",
  "aliases": [
    "CVE-2023-28859"
  ],
  "summary": "redis-py Race Condition due to incomplete fix",
  "details": "redis-py through 4.5.3 leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a non-pipeline operation), and can send response data to the client of an unrelated request. NOTE: this issue exists because of an incomplete fix for CVE-2023-28858.",
  "severity": [

  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "redis"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.5.0"
            },
            {
              "fixed": "4.5.4"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "redis"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.4.0"
            },
            {
              "fixed": "4.4.4"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "redis"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "< 4.3.6"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-28859"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/issues/2665"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/pull/2641"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/redis/redis-py"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/releases/tag/v4.4.4"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/releases/tag/v4.5.4"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2023-03-27T21:31:52Z",
    "nvd_published_at": "2023-03-26T19:15:00Z"
  }
}