{
  "schema_version": "1.4.0",
  "id": "GHSA-7jq8-885h-574r",
  "modified": "2023-07-12T15:30:47Z",
  "published": "2023-07-06T18:30:51Z",
  "aliases": [
    "CVE-2023-37453"
  ],
  "details": "An issue was discovered in the USB subsystem in the Linux kernel through 6.4.2. There is an out-of-bounds and crash in read_descriptors in drivers/usb/core/sysfs.c.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:P/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-37453"
    },
    {
      "type": "WEB",
      "url": "https://lore.kernel.org/all/000000000000c0ffe505fe86c9ca@google.com/T/"
    },
    {
      "type": "WEB",
      "url": "https://lore.kernel.org/all/000000000000e56434059580f86e@google.com/T/"
    },
    {
      "type": "WEB",
      "url": "https://syzkaller.appspot.com/bug?extid=18996170f8096c6174d0"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-125"
    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2023-07-06T17:15:14Z"
  }
}