{
  "schema_version": "1.2.0",
  "id": "GHSA-924m-4pmx-c67h",
  "modified": "2021-09-07T20:34:38Z",
  "published": "2018-07-13T16:01:17Z",
  "aliases": [
    "CVE-2017-1000433"
  ],
  "summary": "High severity vulnerability that affects pysaml2",
  "details": "pysaml2 version 4.4.0 and older accept any password when run with python optimizations enabled. This allows attackers to log in as any user without knowing their password.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pysaml2"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4.5.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-1000433"
    },
    {
      "type": "WEB",
      "url": "https://github.com/rohe/pysaml2/issues/451"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-924m-4pmx-c67h"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2018/07/msg00000.html"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2021/02/msg00038.html"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/201801-11"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/rohe/pysaml2"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-287"
    ],
    "severity": "HIGH",
    "github_reviewed": true
  }
}