{
  "schema_version": "1.4.0",
  "id": "GHSA-q4mp-jvh2-76fj",
  "modified": "2023-09-02T05:03:04Z",
  "published": "2022-11-14T12:00:15Z",
  "aliases": [
    "CVE-2022-45199"
  ],
  "summary": "Pillow subject to DoS via SAMPLESPERPIXEL tag",
  "details": "Pillow starting with 9.2.0 and prior to 9.3.0 allows denial of service via SAMPLESPERPIXEL. A large value in the SAMPLESPERPIXEL tag could lead to a memory and runtime DOS in TiffImagePlugin.py when setting up the context for image decoding. This issue has been patched in version 9.3.0.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pillow"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "9.2.0"
            },
            {
              "fixed": "9.3.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-45199"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/pull/6700"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/commit/00b25fd3ac3648bc28eff5d4c4d816e605e3f05f"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/commit/05b175ef88c22f5c416bc9b8d5b897dea1abbf2c"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/commit/0846bfae48513f2f51ca8547ed3b8954fa501fda"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/commit/13f2c5ae14901c89c38f898496102afd9daeaf6d"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/commit/2444cddab2f83f28687c7c20871574acbb6dbcf3"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/commit/799a6a01052cea3f417a571d7c64cd14acc18c64"
    },
    {
      "type": "WEB",
      "url": "https://bugs.gentoo.org/878769"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2022-42980.yaml"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/python-pillow/Pillow"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/releases/tag/9.3.0"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/202211-10"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-400"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2022-11-15T13:24:05Z",
    "nvd_published_at": "2022-11-14T07:15:00Z"
  }
}