{
  "schema_version": "1.3.0",
  "id": "GHSA-qwqv-j7jr-4hp6",
  "modified": "2023-02-26T14:12:24Z",
  "published": "2022-05-06T00:00:54Z",
  "aliases": [
    "CVE-2022-30284"
  ],
  "summary": "Argument injection in python-libnmap",
  "details": "In the python-libnmap package through 0.7.2 for Python, remote command execution can occur (if used in a client application that does not validate arguments).",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "python-libnmap"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.7.3"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 0.7.2"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-30284"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/savon-noir/python-libnmap"
    },
    {
      "type": "WEB",
      "url": "https://github.com/savon-noir/python-libnmap/releases"
    },
    {
      "type": "WEB",
      "url": "https://libnmap.readthedocs.io/en/latest/process.html#using-libnmap-process"
    },
    {
      "type": "WEB",
      "url": "https://pypi.org/project/python-libnmap/"
    },
    {
      "type": "WEB",
      "url": "https://www.swascan.com/security-advisory-libnmap-2/"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-88"
    ],
    "severity": "CRITICAL",
    "github_reviewed": true,
    "github_reviewed_at": "2022-05-24T20:53:45Z",
    "nvd_published_at": "2022-05-04T22:15:00Z"
  }
}