{
  "schema_version": "1.2.0",
  "id": "GHSA-cq94-qf6q-mf2h",
  "modified": "2022-05-25T03:10:09Z",
  "published": "2018-07-16T16:50:30Z",
  "aliases": [
    "CVE-2017-1000246"
  ],
  "summary": "Moderate severity vulnerability that affects pysaml2",
  "details": "Python package pysaml2 version 4.5.0 and earlier reuses the initialization vector across encryptions in the IDP server, resulting in weak encryption of data.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pysaml2"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4.6.0"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 4.5.0"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-1000246"
    },
    {
      "type": "WEB",
      "url": "https://github.com/rohe/pysaml2/issues/417"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-cq94-qf6q-mf2h"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/rohe/pysaml2"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-330"
    ],
    "severity": "MODERATE",
    "github_reviewed": true
  }
}