{
  "schema_version": "1.2.0",
  "id": "GHSA-7v7w-f7c6-f829",
  "modified": "2022-01-03T15:47:58Z",
  "published": "2021-12-16T21:01:15Z",
  "aliases": [
    "CVE-2021-4111"
  ],
  "summary": "yetiforcecrm is vulnerable to Business Logic Errors",
  "details": "yetiforcecrm is vulnerable to Business Logic Errors.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Packagist",
        "name": "yetiforce/yetiforce-crm"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 6.3.0"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-4111"
    },
    {
      "type": "WEB",
      "url": "https://github.com/yetiforcecompany/yetiforcecrm/commit/c1ad7111a090adfcd5898af40724907adc987acf"
    },
    {
      "type": "WEB",
      "url": "https://huntr.dev/bounties/8afc8981-baff-4082-b640-be535b29eb9a"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/yetiforcecompany/yetiforcecrm"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "HIGH",
    "github_reviewed": true
  }
}