{
  "schema_version": "1.2.0",
  "id": "GHSA-p9wf-3xpg-c9g5",
  "modified": "2021-09-07T17:16:00Z",
  "published": "2021-09-02T17:11:13Z",
  "aliases": [
    "CVE-2021-39371"
  ],
  "summary": "XML External Entity Injection in PyWPS",
  "details": "An XML external entity (XXE) injection in PyWPS before 4.5.0 allows an attacker to view files on the application server filesystem by assigning a path to the entity. OWSLib 0.24.1 may also be affected.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pywps"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4.5.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-39371"
    },
    {
      "type": "WEB",
      "url": "https://github.com/geopython/OWSLib/issues/790"
    },
    {
      "type": "WEB",
      "url": "https://github.com/geopython/pywps/pull/616"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2021/09/msg00001.html"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/geopython/pywps"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-611",
      "CWE-91"
    ],
    "severity": "HIGH",
    "github_reviewed": true
  }
}