{
  "schema_version": "1.3.0",
  "id": "GHSA-4h33-v95w-8vh4",
  "modified": "2022-10-19T04:18:16Z",
  "published": "2022-04-03T00:01:04Z",
  "aliases": [
    "CVE-2020-25691"
  ],
  "summary": "darkhttpd: large mtime crash",
  "details": "A flaw was found in darkhttpd. Invalid error handling allows remote attackers to cause denial-of-service by accessing a file with a large modification date (year 10,000+). The highest threat from this vulnerability is to system availability.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Packagist",
        "name": ""
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-25691"
    },
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1893725"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/emikulic/darkhttpd"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-755"
    ],
    "severity": "MODERATE",
    "github_reviewed": false
  }
}