{
  "schema_version": "1.2.0",
  "id": "GHSA-vx6v-2rg6-865h",
  "modified": "2021-08-17T22:13:42Z",
  "published": "2019-08-27T17:39:33Z",
  "aliases": [
    "CVE-2019-15486"
  ],
  "summary": "Cross-site Scripting in django-js-reverse",
  "details": "django-js-reverse (aka Django JS Reverse) before 0.9.1 has XSS via js_reverse_inline.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django-js-reverse"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.9.1"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-15486"
    },
    {
      "type": "WEB",
      "url": "https://github.com/ierror/django-js-reverse/pull/81"
    },
    {
      "type": "WEB",
      "url": "https://github.com/ierror/django-js-reverse/compare/v0.9.0...v0.9.1"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-79"
    ],
    "severity": "MODERATE",
    "github_reviewed": true
  }
}